
CREATE TABLE IF NOT EXISTS tb_user_block_removed (
    block_remove_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    block_reason VARCHAR(255),
    unblock_reason VARCHAR(255),
    blocked_at TIMESTAMP,
    unblocked_at TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tb_users_deleted (
    user_delete_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
