server:
    port: 5000
    tomcat:
        connection-timeout: 20000 # Tempo de timeout para aceitar uma conexão (em milissegundos)
        keep-alive-timeout: 15000 # Tempo máximo para manter a conexão aberta sem enviar dados
        max-keep-alive-requests: 100 # Número máximo de requisições para uma conexão persistente
        max-http-header-size: 8192
spring:
    application:
        name: User
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/users_database?currentSchema=public
        username: ${PG_USER}
        password: ${PG_PASS}
        pool:
            initial-size: 5
            max-size: 20
            max-wait: 30000
    r2dbc-migrate:
        locations: classpath:/db/sql/migrations
    flyway:
        enabled: true
        locations: classpath:/db/sql/migrations
    elasticsearch:
        uris: http://localhost:9200
    datasource:
        url: jdbc:postgresql://localhost:5432/users_database
        username: ${PG_USER}
        password: ${PG_PASS}
        driver-class-name: org.postgresql.Driver
logging:
    level:
        org.springframework.data.r2dbc.core.R2dbcEntityTemplate: DEBUG
        org.springframework.r2dbc.core.DatabaseClient: DEBUG
        org.springframework: ERROR
        org.hibernate: DEBUG
        root: DEBUG
        org.springframework.web: ERROR
        org.flywaydb: DEBUG
        org.apache.coyote: ERROR # Validar o motivos dos erros sem isso...
        org.apache.tomcat: ERROR # Validar o motivos dos erros sem isso...
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
