Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
Database:
  MongoDb:
    ConnectionString: mongodb://mongodbs:27017
    DatabaseName: LiveStream-dev-container
    CollectionName: Live-dev-container-v0-beta
Cache:
  Redis:
    ConnectionString: redis-container:6379
AllowedHosts: "*"