Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
Database:
  MongoDb:
    ConnectionString: mongodb://mongodb:27017
    DatabaseName: LiveStream-prod
    CollectionName: Live-prod-v0-beta
Storage:
  Lives:
    Path: app/data/live
Services:
  LiveStream:
    FFmpeg:
      HlsUrl: rtmp://nginx-rtmp:1935/live/usuario_exemplo/Minha_Live_Incrivel
AllowedHosts: "*"