Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
Database:
  MongoDb:
    ConnectionString: mongodb://mongodbs:27017
    DatabaseName: LiveStream-dev-container
    CollectionName: Live-dev-container-v0-beta
Storage:
  PhysicalStorage:
    BaseHlsPath: /app/hls/
    BaseVideoPath: /app/video/
    StorageType: Physical-Container

AllowedHosts: "*"